name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          git config --global user.email "laila.atrmouh@gmail.com"
          git config --global user.name "leiluspocus"
          git checkout --orphan gh-pages
          git --no-pager add --all
          git --no-pager commit -m "Deploy to GitHub Pages"
          git --no-pager push origin HEAD:gh-pages --force
